multinode: false

modelArtifacts:
  #uri: "hf://Qwen/Qwen3-32B"
  uri: "hf://Qwen/Qwen3-8B"
  name: "Qwen/Qwen3-8B"
  size: 80Gi
  authSecretName: "llm-d-hf-token"

routing:
  proxy:
    enabled: false  # removes sidecar from deployment - no PD in inference scheduling

accelerator:  # controls specialized hardware Type
  type: nvidia

decode:
  create: true
  parallelism:
    tensor: 1
    data: 1
  replicas: 1
  monitoring:
    podmonitor:
      enabled: true
      portName: "vllm"  # decode vLLM service port (from routing.proxy.targetPort)
      path: "/metrics"
      interval: "30s"
  containers:
    - name: "vllm"
      image: quay.io/kfirt/vllm-offloading:storage-v0.14.1
      modelCommand: custom
      command:
        - /bin/sh
        - '-c'
      args:
        - |
          set -x
          exec vllm serve Qwen/Qwen3-8B \
            --port 8000 \
            --served-model-name "Qwen/Qwen3-8B" \
            --block-size 64 \
            --kv-events-config "{\"enable_kv_cache_events\":true,\"publisher\":\"zmq\",\"endpoint\":\"tcp://gaie-${GAIE_RELEASE_NAME_POSTFIX}-epp.${NAMESPACE}.svc.cluster.local:5557\",\"topic\":\"kv@${POD_IP}@Qwen/Qwen3-8B\"}" \
            --disable-uvicorn-access-log \
            --kv-transfer-config '{"kv_connector":"OffloadingConnector","kv_role":"kv_both","kv_connector_extra_config":{"spec_name":"SharedStorageOffloadingSpec","spec_module_path":"llmd_fs_backend.spec","shared_storage_path":"/mnt/kv-cache-storage/","block_size":512,"threads_per_gpu":"64"}}' \
            --gpu-memory-utilization=0.95
      env:
        - name: GAIE_RELEASE_NAME_POSTFIX  # index 0 matters because of set in helmfile
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace  # assumed to be the same as the EPP's
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: STORAGE_CONNECTOR_DEBUG
          value: "1"
        - name: VLLM_LOGGING_LEVEL
          value: DEBUG
        - name: TRITON_CACHE_DIR
          value: /.triton-cache
      ports:
        - containerPort: 8000
          name: vllm
          protocol: TCP
      resources:
        limits:
  #        nvidia.com/gpu: '2' # added automatically from 'parallelism'
          cpu: '32'
          memory: 100Gi
        requests:
  #        nvidia.com/gpu: '2' # added automatically from 'parallelism'
          cpu: '32'
          memory: 100Gi
      mountModelVolume: true
      volumeMounts:
        - name: metrics-volume
          mountPath: /.config
        - name: shm
          mountPath: /dev/shm
        - name: torch-compile-cache
          mountPath: /.cache
        - name: triton-cache
          mountPath: /.triton-cache
        - name: kvc-path
          mountPath: /mnt/kv-cache-storage/
      startupProbe:
        httpGet:
          path: /v1/models
          port: vllm
        initialDelaySeconds: 15
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 60
      livenessProbe:
        httpGet:
          path: /health
          port: vllm
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /v1/models
          port: vllm
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 3
  volumes:
    - name: metrics-volume
      emptyDir: {}
    - name: torch-compile-cache
      emptyDir: {}
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 20Gi
    - name: triton-cache
      emptyDir: {}
    - name: kvc-path
      persistentVolumeClaim:
        claimName: afm-pvc-n3

# PD disabled in this example
prefill:
  create: false
